# Generated by Django 4.2.5 on 2023-10-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0002_bookdb_delete_categorydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
