# Generated by Django 4.2.5 on 2023-10-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0003_detailsdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsdb',
            name='Book_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Book_Image'),
        ),
        migrations.AddField(
            model_name='detailsdb',
            name='Content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detailsdb',
            name='Definition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detailsdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
