# Generated by Django 4.2.5 on 2023-10-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0004_detailsdb_book_image_detailsdb_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailsdb',
            old_name='Book_Name',
            new_name='BookName',
        ),
        migrations.RenameField(
            model_name='detailsdb',
            old_name='Content',
            new_name='Genres',
        ),
    ]
