# Generated by Django 4.2.5 on 2023-10-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0005_rename_book_name_detailsdb_bookname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdb',
            old_name='BookName',
            new_name='MyApp',
        ),
    ]
