# Generated by Django 4.2.5 on 2023-10-09 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0006_rename_bookname_bookdb_myapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdb',
            old_name='MyApp',
            new_name='BookName',
        ),
    ]
